---
version: '2'
services:
  common:
    build: "."
    environment:
      DATABASE_URL: mongodb://:O-LjFRe3CuYNnktsosCvyw@db:27017/
      NODE_ENV: production
  app:
    extends:
      service: common
    links:
    - db
    ports:
    - 1337:1337
    command: node app.js --prod
  db:
    image: mongo
    environment:
      MONGODB_PASSWORD: O-LjFRe3CuYNnktsosCvyw
